/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package de.hska.iwi.bdelab.schema;

import org.apache.commons.lang3.builder.HashCodeBuilder;
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class PageView implements org.apache.thrift.TBase<PageView, PageView._Fields>, java.io.Serializable, Cloneable, Comparable<PageView> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PageView");

  private static final org.apache.thrift.protocol.TField UID_FIELD_DESC = new org.apache.thrift.protocol.TField("uid", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("page", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField NONCE_FIELD_DESC = new org.apache.thrift.protocol.TField("nonce", org.apache.thrift.protocol.TType.I32, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PageViewStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PageViewTupleSchemeFactory());
  }

  private UserID uid; // required
  private Page page; // required
  private int nonce; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    UID((short)1, "uid"),
    PAGE((short)2, "page"),
    NONCE((short)3, "nonce");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // UID
          return UID;
        case 2: // PAGE
          return PAGE;
        case 3: // NONCE
          return NONCE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __NONCE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.UID, new org.apache.thrift.meta_data.FieldMetaData("uid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, UserID.class)));
    tmpMap.put(_Fields.PAGE, new org.apache.thrift.meta_data.FieldMetaData("page", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Page.class)));
    tmpMap.put(_Fields.NONCE, new org.apache.thrift.meta_data.FieldMetaData("nonce", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PageView.class, metaDataMap);
  }

  public PageView() {
  }

  public PageView(
    UserID uid,
    Page page,
    int nonce)
  {
    this();
    this.uid = uid;
    this.page = page;
    this.nonce = nonce;
    set_nonce_isSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PageView(PageView other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.is_set_uid()) {
      this.uid = new UserID(other.uid);
    }
    if (other.is_set_page()) {
      this.page = new Page(other.page);
    }
    this.nonce = other.nonce;
  }

  public PageView deepCopy() {
    return new PageView(this);
  }

  @Override
  public void clear() {
    this.uid = null;
    this.page = null;
    set_nonce_isSet(false);
    this.nonce = 0;
  }

  public UserID get_uid() {
    return this.uid;
  }

  public void set_uid(UserID uid) {
    this.uid = uid;
  }

  public void unset_uid() {
    this.uid = null;
  }

  /** Returns true if field uid is set (has been assigned a value) and false otherwise */
  public boolean is_set_uid() {
    return this.uid != null;
  }

  public void set_uid_isSet(boolean value) {
    if (!value) {
      this.uid = null;
    }
  }

  public Page get_page() {
    return this.page;
  }

  public void set_page(Page page) {
    this.page = page;
  }

  public void unset_page() {
    this.page = null;
  }

  /** Returns true if field page is set (has been assigned a value) and false otherwise */
  public boolean is_set_page() {
    return this.page != null;
  }

  public void set_page_isSet(boolean value) {
    if (!value) {
      this.page = null;
    }
  }

  public int get_nonce() {
    return this.nonce;
  }

  public void set_nonce(int nonce) {
    this.nonce = nonce;
    set_nonce_isSet(true);
  }

  public void unset_nonce() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __NONCE_ISSET_ID);
  }

  /** Returns true if field nonce is set (has been assigned a value) and false otherwise */
  public boolean is_set_nonce() {
    return EncodingUtils.testBit(__isset_bitfield, __NONCE_ISSET_ID);
  }

  public void set_nonce_isSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __NONCE_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case UID:
      if (value == null) {
        unset_uid();
      } else {
        set_uid((UserID)value);
      }
      break;

    case PAGE:
      if (value == null) {
        unset_page();
      } else {
        set_page((Page)value);
      }
      break;

    case NONCE:
      if (value == null) {
        unset_nonce();
      } else {
        set_nonce((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case UID:
      return get_uid();

    case PAGE:
      return get_page();

    case NONCE:
      return Integer.valueOf(get_nonce());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case UID:
      return is_set_uid();
    case PAGE:
      return is_set_page();
    case NONCE:
      return is_set_nonce();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PageView)
      return this.equals((PageView)that);
    return false;
  }

  public boolean equals(PageView that) {
    if (that == null)
      return false;

    boolean this_present_uid = true && this.is_set_uid();
    boolean that_present_uid = true && that.is_set_uid();
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (!this.uid.equals(that.uid))
        return false;
    }

    boolean this_present_page = true && this.is_set_page();
    boolean that_present_page = true && that.is_set_page();
    if (this_present_page || that_present_page) {
      if (!(this_present_page && that_present_page))
        return false;
      if (!this.page.equals(that.page))
        return false;
    }

    boolean this_present_nonce = true;
    boolean that_present_nonce = true;
    if (this_present_nonce || that_present_nonce) {
      if (!(this_present_nonce && that_present_nonce))
        return false;
      if (this.nonce != that.nonce)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    HashCodeBuilder builder = new HashCodeBuilder();

    boolean present_uid = true && (is_set_uid());
    builder.append(present_uid);
    if (present_uid)
      builder.append(uid);

    boolean present_page = true && (is_set_page());
    builder.append(present_page);
    if (present_page)
      builder.append(page);

    boolean present_nonce = true;
    builder.append(present_nonce);
    if (present_nonce)
      builder.append(nonce);

    return builder.toHashCode();
  }

  @Override
  public int compareTo(PageView other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(is_set_uid()).compareTo(other.is_set_uid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_uid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.uid, other.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(is_set_page()).compareTo(other.is_set_page());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_page()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.page, other.page);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(is_set_nonce()).compareTo(other.is_set_nonce());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (is_set_nonce()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.nonce, other.nonce);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("PageView(");
    boolean first = true;

    sb.append("uid:");
    if (this.uid == null) {
      sb.append("null");
    } else {
      sb.append(this.uid);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("page:");
    if (this.page == null) {
      sb.append("null");
    } else {
      sb.append(this.page);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("nonce:");
    sb.append(this.nonce);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (!is_set_uid()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'uid' is unset! Struct:" + toString());
    }

    if (!is_set_page()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'page' is unset! Struct:" + toString());
    }

    if (!is_set_nonce()) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'nonce' is unset! Struct:" + toString());
    }

    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PageViewStandardSchemeFactory implements SchemeFactory {
    public PageViewStandardScheme getScheme() {
      return new PageViewStandardScheme();
    }
  }

  private static class PageViewStandardScheme extends StandardScheme<PageView> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, PageView struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // UID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.uid = new UserID();
              struct.uid.read(iprot);
              struct.set_uid_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.page = new Page();
              struct.page.read(iprot);
              struct.set_page_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // NONCE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.nonce = iprot.readI32();
              struct.set_nonce_isSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, PageView struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.uid != null) {
        oprot.writeFieldBegin(UID_FIELD_DESC);
        struct.uid.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.page != null) {
        oprot.writeFieldBegin(PAGE_FIELD_DESC);
        struct.page.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(NONCE_FIELD_DESC);
      oprot.writeI32(struct.nonce);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PageViewTupleSchemeFactory implements SchemeFactory {
    public PageViewTupleScheme getScheme() {
      return new PageViewTupleScheme();
    }
  }

  private static class PageViewTupleScheme extends TupleScheme<PageView> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PageView struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      struct.uid.write(oprot);
      struct.page.write(oprot);
      oprot.writeI32(struct.nonce);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PageView struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.uid = new UserID();
      struct.uid.read(iprot);
      struct.set_uid_isSet(true);
      struct.page = new Page();
      struct.page.read(iprot);
      struct.set_page_isSet(true);
      struct.nonce = iprot.readI32();
      struct.set_nonce_isSet(true);
    }
  }

}

